### ISSUE TITLE
Rustic support

### ISSUE THREAD

**Issue by Asstuba** [Real-Gecko/XPFromHarvest#3]
If you would be so kind -- Rustic has a few crops that don't appear to be standard/recognized:

Fully grown blocks are:
rustic:tomato_crop@3
rustic:chili_crop@3
rustic@grape_leaves@11

There are berries and what not as well, but that is more foraging than harvesting from crops.

**Comment by Real-Gecko** [comment]
Try version 1.2.0, there's an option in config now where you can put any crop you want with any age you want. If you enable "Curiosity" mode in config, sneak right click on a crop will show you all needed info need for that:
```
    S:"Crops List" <
        minecraft:potatoes[age=7]
        minecraft:carrots[age=7]
        minecraft:wheat[age=7]
        minecraft:beetroots[age=3]
        minecraft:nether_wart[age=3]
        xlfoodmod:pepper_plant[age=7]
        xlfoodmod:cucumber_plant[age=7]
        xlfoodmod:rice_plant[age=7]
        xlfoodmod:corn_plant[age=7]
        xlfoodmod:lettuce_plant[age=7]
        xlfoodmod:tomato_plant[age=7]
        xlfoodmod:strawberry_plant[age=7]
        xlfoodmod:corn_plant[age=7]
     >
```
