### ISSUE TITLE
Support for PamHarvestCraft (1.12.2)

### ISSUE THREAD

**Issue by LucioneWolff** [Real-Gecko/XPFromHarvest#4]
I don't know if I registered all the seeds of "PamHarvestCraft" since I got the information with the config of the same mod.
I have a problem with minecraft farming and it is that the probability of getting xp from there is very low, however with PHC I have a 100% chance
Any solution?
(GoogleTranslator)
I did this myself in case someone wants to add it* 
minecraft:potato[age=7]
minecraft:carrot[age=7]
minecraft:wheat[age=7]
minecraft:beetroots[age=3]
minecraft:nether_wart[age=3]
harvestcraft:pamcactusfruitcrop[age=3]
harvestcraft:pamagavecrop[age=3]
harvestcraft:pamsisalcrop[age=3]
harvestcraft:pamcassavacrop[age=3]
harvestcraft:pamchickpeacrop[age=3]
harvestcraft:pamlentilcrop[age=3]
harvestcraft:pamraspberrycrop[age=3]
harvestcraft:pamoatscrop[age=3]
harvestcraft:pamryecrop[age=3]
harvestcraft:pamcelerycrop[age=3]
harvestcraft:pampeascrop[age=3]
harvestcraft:pambeetcrop[age=3]
harvestcraft:pamrutabagacrop[age=3]
harvestcraft:pambroccolicrop[age=3]
harvestcraft:pamcauliflowercrop[age=3]
harvestcraft:pamcabbagecrop[age=3]
harvestcraft:pamspinachcrop[age=3]
harvestcraft:pamcottoncrop[age=3]
harvestcraft:pamhuckleberrycrop[age=3]
harvestcraft:pamkohlrabicrop[age=3]
harvestcraft:pamquinoacrop[age=3]
harvestcraft:pamjunipercrop[age=3]
harvestcraft:pamwhitemushroomcrop[age=3]
harvestcraft:pamblackberrycrop[age=3]
harvestcraft:pamzucchinicrop[age=3]
harvestcraft:pamradishcrop[age=3]
harvestcraft:pamrhubarbcrop[age=3]
harvestcraft:pamtealeafcrop[age=3]
harvestcraft:pamgarliccrop[age=3]
harvestcraft:pamsweetpotatocrop[age=3]
harvestcraft:pamturnipcrop[age=3]
harvestcraft:pamspiceleafcrop[age=3]
harvestcraft:pambeancrop[age=3]
harvestcraft:pamleekcrop[age=3]
harvestcraft:pamscallioncrop[age=3]
harvestcraft:pamtomatocrop[age=3]
harvestcraft:pamjutecrop[age=3]
harvestcraft:pambrusselsproutcrop[age=3]
harvestcraft:pamspiceleafcrop[age=3]
harvestcraft:pamblueberrycrop[age=3]
harvestcraft:pamasparaguscrop[age=3]
harvestcraft:pamcranberrycrop[age=3]
harvestcraft:pamricecrop[age=3]
harvestcraft:pamseaweedcrop[age=3]
harvestcraft:pamwaterchestnutcrop[age=3]
harvestcraft:pamokracrop[age=3]
harvestcraft:pamcottoncrop[age=3]
harvestcraft:pamkalecrop[age=3]
harvestcraft:pammilletcrop[age=3]
harvestcraft:pamjicamacrop[age=3]
harvestcraft:pamgreengrapecrop[age=3]
harvestcraft:pammulberrycrop[age=3]
harvestcraft:pamtomatillocrop[age=3]
harvestcraft:pamgrapecrop[age=3]
harvestcraft:pampineapplecrop[age=3]
harvestcraft:pamkiwicrop[age=3]
harvestcraft:pamsesameseedscrop[age=3]
harvestcraft:pamcurryleafcrop[age=3]
harvestcraft:pambambooshootcrop[age=3]
harvestcraft:pamcantaloupecrop[age=3]
harvestcraft:pamgingercrop[age=3]
harvestcraft:pamcoffeebeancrop[age=3]
harvestcraft:pamsoybeancrop[age=3]
harvestcraft:pameggplantcrop[age=3]
harvestcraft:pamkenafcrop[age=3]
harvestcraft:pamarrowrootcrop[age=3]
harvestcraft:pamtarocrop[age=3]
harvestcraft:pamstrawberrycrop[age=3]
harvestcraft:pambarleycrop[age=3]
harvestcraft:pamcorncrop[age=3]
harvestcraft:pamcucumbercrop[age=3]
harvestcraft:pamwintersquashcrop[age=3]
harvestcraft:pammustardseedscrop[age=3]
harvestcraft:pamonioncrop[age=3]
harvestcraft:pamparsnipcrop[age=3]
harvestcraft:pampeanutcrop[age=3]
harvestcraft:pamlettucecrop[age=3]
harvestcraft:pamartichokecrop[age=3]
harvestcraft:pambellpeppercrop[age=3]
harvestcraft:pamchilipeppercrop[age=3]
harvestcraft:pamflaxcrop[age=3]
harvestcraft:pamamaranthcrop[age=3]
harvestcraft:pamelderberrycrop[age=3]

**Comment by Real-Gecko** [comment]
I tried it out and did not find any issues. I've set chance to 10 and XP was barely dropping during harvest bot with vanilla crops and at least with cucumber and blackberry.
