### ISSUE TITLE
Exception caught during firing event: null

### ISSUE THREAD

**Issue by Pi0nStEaM** [Real-Gecko/XPFromHarvest#8]
So I launched my server, joined, then proceeded to harvest wheat to test the mod.
Nothing noticeably breaks in game, but the server throws this error.
(Error in .txt file)

The error was not instantly thrown upon harvesting wheat crops individually however it only gets thrown when harvesting a bunch at a time. (like running through a field and holding down right click)
[Exception caught during firing event null.txt](https://github.com/Real-Gecko/XPFromHarvest/files/6551141/Exception.caught.during.firing.event.null.txt)

**Comment by Real-Gecko** [comment]
You have some other mod that tries to catch right click on a block event. There's currently a bunch of mods that support simple harvest functionality, for example Quark developers added this functionality some time ago. Make sure you go through all of your mods and disable `Simple Harvest` like functionality in all of them. Otherwise you'll either get exceptions or won't receive XP with simple harvest enabled.

**Comment by Pi0nStEaM** [comment]
Alright! I'll double check.  Sorry for the late response.

**Comment by JustinTheBob** [comment]
> Alright! I'll double check. Sorry for the late response.

Did u figure out which mod it was? I have the same issue and have 94 mods...don't exactly know what mods add this. Thank you!

**Comment by Real-Gecko** [comment]
Try running through the log file seeking for `java.util.ConcurrentModificationException` and see which one causes trouble. `Listeners` list might be helpful.

**Comment by JustinTheBob** [comment]
Yea I looked at both. Didn't find a mod that does the crouch right-click to break and re-plant crops. Anything U see here being the issue?
java.util.ConcurrentModificationException Log:
https://pastebin.com/q4s6SA3z

Listeners Log:
https://pastebin.com/fUipNpiu

Thank you for taking the time.

**Comment by Real-Gecko** [comment]
@JustinTheBob the only thing I can propose is to take a look at this mods:

- architectury
- torchslabsmod
- tinyredstone
- spawnermod
- patchouli
- buildersaddition
- creaturesandbeasts
- chiselsandbits
- easyvillagers
- pitweaks
- mob_grinding_utils
- multibeds
- worldedit

Strategy is following:

1. Create a new MC installation ([https://multimc.org/](https://multimc.org/) to the rescue)
2. Add this mod to the installation
3. Check if everything works
4. Add one mod from the list above to installtion
5. Check that everything works
6. Go to step 4 if everything is OK and not all mods added
7. If something goes wrong with some particular mod, check it's settings and see if you can live without right click functionality of the mod and if you can disable it.
8. Report me the name of the mod so I can try to fix things on my side.

**Comment by JustinTheBob** [comment]
> @JustinTheBob the only thing I can propose is to take a look at this mods:
> 
> * architectury
> * torchslabsmod
> * tinyredstone
> * spawnermod
> * patchouli
> * buildersaddition
> * creaturesandbeasts
> * chiselsandbits
> * easyvillagers
> * pitweaks
> * mob_grinding_utils
> * multibeds
> * worldedit
> 
> Strategy is following:
> 
> 1. Create a new MC installation (https://multimc.org/ to the rescue)
> 2. Add this mod to the installation
> 3. Check if everything works
> 4. Add one mod from the list above to installtion
> 5. Check that everything works
> 6. Go to step 4 if everything is OK and not all mods added
> 7. If something goes wrong with some particular mod, check it's settings and see if you can live without right click functionality of the mod and if you can disable it.
> 8. Report me the name of the mod so I can try to fix things on my side.

Will do thank you. I’ll try that tonight after I get off work. Thank you.

**Comment by JustinTheBob** [comment]
Okay so I tested it a little bit, and figured out that if I disable the simple farming in config and try to right click the plants no spam occures. As well ass ofc the plants don't break and re-plant. So no other mods are doing the simple farming. All of the "right click" error spam is just I guess the game thinking all those other mods right click features are trying to be used? Even though they only use those right clicks at certain times on certain blocks(none being plants). I guess I just have to deal with the log spam. Not much I can do and want all those mods aswell so I can just deal with it. Not like it breaks the game anyways. Thank you.

**Comment by Real-Gecko** [comment]
There's `PlayerInteractEvent.RightClickBlock event` in Forge. So every mod trying to handle right clicking (no matter of functionality it tries to implement) has to subscribe to this event. And then mods process the event depending on priority. This mod uses `EventPriority.HIGHEST`. So I guess there's some kind of interference in that process. But of course if everything works fine you may ignore log spam. Worse is when some functionality does not work.

**Comment by JustinTheBob** [comment]
> There's `PlayerInteractEvent.RightClickBlock event` in Forge. So every mod trying to handle right clicking (no matter of functionality it tries to implement) has to subscribe to this event. And then mods process the event depending on priority. This mod uses `EventPriority.HIGHEST`. So I guess there's some kind of interference in that process. But of course if everything works fine you may ignore log spam. Worse is when some functionality does not work.

That’s okay, there’s probably nothing that can be done about that when having a lot of mods. I just wonder how big modpack s with over 150 mods fix issues like these and make all mods work together lol

**Comment by Real-Gecko** [comment]
Well, I guess they #@%* a lot before they can put it all together :D

**Comment by JustinTheBob** [comment]
> Well, I guess they #@%* a lot before they can put it all together :D

What is #@%*? 😂 like edit a lot of stuff?

**Comment by Real-Gecko** [comment]
> > Well, I guess they #@%* a lot before they can put it all together :D
> 
> What is #@%*? joy like edit a lot of stuff?

Definitely :D

**Comment by Real-Gecko** [comment]
Hey there, I've released version 1.2.2 which has the issue fixed. Turns out it was not other mod interference, but my lack of knowledge of Java exceptions. Will upload to CurseForge shortly.
