### ISSUE TITLE
1.16.5 Port - I made one :)

### ISSUE THREAD

**Issue by ghost** [Real-Gecko/XPFromHarvest#9]
Sorry to bother you through the issues page - but I didn't know where to go for this - I really wanted a mod like this for forge 1.16.5 and decided to build one off your code (test my ability to code - ish). It ended up successful, however I didn't just want to post it to CurseForge or anywhere else without seeing if you already had that in the works... rather not step on your toes.

The only differences between my project and yours currently is I do not have the Curiosity Mode, and the crop list cannot be specified - as long as the block is child to CropsBlock the simple harvest works.

Anyway hope this finds you in good health, if you can, please get back to me at your earliest convenience.

**Comment by Luicuelo** [comment]
I also build a version. I did not read your comment and I thought the same, I love this mod and I wanted it to be in 1.16.5.
I pull-request so real-gecko can import it if he wants.

**Comment by Real-Gecko** [comment]
Thanks, for help.
